### ISSUE TITLE
[BUG] Profile cloning (and importing) not working

### ISSUE THREAD

**Issue by Cheerpipe** [Artemis-RGB/Artemis#627]
https://user-images.githubusercontent.com/972765/122448880-3ad29500-cf73-11eb-9c44-15d85cdc609c.mp4

[11:12] Pipe: Artemis.Core.ArtemisCoreException: Cannot find profile named: Noise - copy ID: d59d4c3c-fa13-46c9-bf45-f899fea21874
   at Profile Artemis.Core.Services.ProfileService.ActivateProfile(ProfileConfiguration profileConfiguration) in D:/Repos/Artemis/src/Artemis.Core/Services/Storage/ProfileService.cs:line 308
   at void Artemis.UI.Shared.Services.ProfileEditorService.ChangeSelectedProfileConfiguration(ProfileConfiguration profileConfiguration) in D:/Repos/Artemis/src/Artemis.UI.Shared/Services/ProfileEditorService.cs:line 160
   at void Artemis.UI.Screens.Sidebar.SidebarViewModel.SelectProfileConfiguration(ProfileConfiguration profileConfiguration) in D:/Repos/Artemis/src/Artemis.UI/Screens/Sidebar/SidebarViewModel.cs:line 151
   at void Artemis.UI.Screens.Sidebar.SidebarCategoryViewModel.set_SelectedProfileConfiguration(SidebarProfileConfigurationViewModel value) in D:/Repos/Artemis/src/Artemis.UI/Screens/Sidebar/SidebarCategoryViewModel.cs:line 86
[11:47] Spoinky: Odd, I'm getting that too
[11:47] Spoinky: Duplicating worked fine before :thonk:

**Comment by Cheerpipe** [comment]
Here is where the profile data is not being saved into profilerepository because makeUnique is true for clone and import operations

            if (**!makeUnique &&** _profileRepository.Get(profileEntity.Id) == null)
                _profileRepository.Add(profileEntity);

**Comment by vaaski** [comment]
I am running into the same issue with a slightly different sounding error message.

https://user-images.githubusercontent.com/17879327/122685476-e0a03100-d20b-11eb-94e8-f72eac2786a5.mp4

<details>
<summary>full log</summary>

```
Artemis.Core.ArtemisCoreException: Cannot import this profile without makeUnique being true
   at Artemis.Core.Services.ProfileService.ImportProfile(ProfileCategory category, ProfileConfigurationExportModel exportModel, Boolean makeUnique, Boolean markAsFreshImport, String nameAffix) in D:\a\1\s\Artemis\src\Artemis.Core\Services\Storage\ProfileService.cs:line 538
   at Artemis.UI.Screens.Sidebar.SidebarProfileConfigurationViewModel.Duplicate() in D:\a\1\s\Artemis\src\Artemis.UI\Screens\Sidebar\SidebarProfileConfigurationViewModel.cs:line 103
--- End of stack trace from previous location ---
   at Stylet.Xaml.ActionBase.InvokeTargetMethod(Object[] parameters)
   at Stylet.Xaml.CommandAction.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

</details>

**Comment by SpoinkyNL** [comment]
Please try build 20210625.2 or higher, it should be fixed now

**Comment by Cheerpipe** [comment]
Clone: Working 

Import:Working but, Artemis is applying adaptions to my own exported Profiles so if I export-import a profile. It won't look the same.

**Comment by SpoinkyNL** [comment]
Hmm yeah that's to be expected, adaption hints are always applied on fresh imports.
I guess I could check to see if the profile ID already exists and then assume the profile came from the same PC, but that's kind of weird hidden behaviour, don't you think?

**Comment by Cheerpipe** [comment]
Would it be too hard to apply adaptions only if a layer is referencing a device/led that doesn't exists? (in a layer basis)
