### ISSUE TITLE
Corsair Device Provider failed to enable

### ISSUE THREAD

**Issue by sofiethetransgirl** [Artemis-RGB/Artemis#642]
Using version 2.0-719d95 build 20210711.1 on Windows 10.

In the setup wizard or in the Plugins menu, if I try to check the "Feature enabled" box for Corsair Device Provider, it fails to check and shows an error icon:

![image](https://user-images.githubusercontent.com/87421136/125604473-e2df7b5c-5688-4dab-bd04-c545bb78da54.png)

Clicking the icon opens a window that says "Feature failed to enable" and shows this error message:

```
System.AggregateException: One or more errors occurred. (RGB.NET threw exception: Error in the application.)
 ---> Artemis.Core.ArtemisPluginException: RGB.NET threw exception: Error in the application.
 ---> RGB.NET.Devices.Corsair.CUEException: Error in the application.
   --- End of inner exception stack trace ---
   at Artemis.Core.Services.RgbService.AddDeviceProvider(IRGBDeviceProvider deviceProvider) in D:\a\1\s\Artemis\src\Artemis.Core\Services\RgbService.cs:line 168
   at Artemis.Plugins.Devices.Corsair.CorsairDeviceProvider.Enable() in D:\a\1\s\Artemis.Plugins\src\Devices\Artemis.Plugins.Devices.Corsair\CorsairDeviceProvider.cs:line 40
   at Artemis.Core.PluginFeature.InternalEnable() in D:\a\1\s\Artemis\src\Artemis.Core\Plugins\PluginFeature.cs:line 190
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Artemis.Core.PluginFeature.SetEnabled(Boolean enable, Boolean isAutoEnable) in D:\a\1\s\Artemis\src\Artemis.Core\Plugins\PluginFeature.cs:line 164
   at Artemis.Core.Services.PluginManagementService.EnablePluginFeature(PluginFeature pluginFeature, Boolean saveState, Boolean isAutoEnable) in D:\a\1\s\Artemis\src\Artemis.Core\Services\PluginManagementService.cs:line 611
```

I have tried multiple times, including after reloading the plugin and after re-installing Artemis, but issue persists.

**Comment by SpoinkyNL** [comment]
Hi there, please make sure the SDK is enabled in iCUE

![image](https://user-images.githubusercontent.com/8858506/125642312-391cb2bf-d295-4597-9dfd-bdc59e28b0d9.png)

There was a recent update in which some people have had trouble getting the SDK to work. If this doesn't help try reinstalling iCUE
