### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by lilman2727** [Artemis-RGB/Artemis#647]
Whenever I turn on my PC and start Artemis, I immediately get this error message 3 times. However Artemis seems to be working just fine after I close these error windows. I am using a Ryzen 7 2700 with an AMD RX 570, using software rendering. Plugin features turned on are Asus and OpenRGB. 
System.ArgumentException: Must create DependencySource on same Thread as the DependencyObject.
   at System.Windows.DependencyObject.ValidateSources(DependencyObject d, DependencySource[] newSources, Expression expr)
   at System.Windows.Expression.ChangeSources(DependencyObject d, DependencyProperty dp, DependencySource[] newSources)
   at System.Windows.Data.BindingExpressionBase.ChangeSources(WeakDependencySource[] newSources)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.RefreshValue()
   at MS.Internal.Data.ClrBindingWorker.ScheduleTransferOperation(Object arg)
   at MS.Internal.Data.DataBindEngine.ProcessCrossThreadRequests()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by SpoinkyNL** [comment]
Hey there,

Could you provide me with your logs?
You can find them at `C:\ProgramData\Artemis\logs`
