### ISSUE TITLE
corsair plugin error

### ISSUE THREAD

**Issue by Volanaro** [Artemis-RGB/Artemis#689]
im getting an error when trying to enable the corsair device provider

` at Artemis.Core.Services.RgbService.AddDeviceProvider(IRGBDeviceProvider deviceProvider) in D:\a\1\s\Artemis\src\Artemis.Core\Services\RgbService.cs:line 182
2022-02-19 17:50:14.995 [DBG] [Artemis.Core.Services.RgbService] Creating SKTexture with graphics context VulkanContext
2022-02-19 17:50:14.996 [WRN] [Artemis.Core.Services.PluginManagementService] Plugin feature 'Artemis.Plugins.Devices.Corsair.CorsairDeviceProvider - Corsair Devices v1.0.1.718 - 926629ab-8170-42f3-be18-22c694aa91cd' failed to enable.
System.AggregateException: One or more errors occurred. (RGB.NET threw exception: Error in the application.)
 ---> Artemis.Core.ArtemisPluginException: RGB.NET threw exception: Error in the application.
 ---> RGB.NET.Devices.Corsair.CUEException: Error in the application.
   --- End of inner exception stack trace ---
   at Artemis.Core.Services.RgbService.AddDeviceProvider(IRGBDeviceProvider deviceProvider) in D:\a\1\s\Artemis\src\Artemis.Core\Services\RgbService.cs:line 182
   at Artemis.Plugins.Devices.Corsair.CorsairDeviceProvider.Enable() in D:\a\1\s\Artemis.Plugins\src\Devices\Artemis.Plugins.Devices.Corsair\CorsairDeviceProvider.cs:line 42
   at Artemis.Core.PluginFeature.InternalEnable() in D:\a\1\s\Artemis\src\Artemis.Core\Plugins\PluginFeature.cs:line 178
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Artemis.Core.PluginFeature.SetEnabled(Boolean enable, Boolean isAutoEnable) in D:\a\1\s\Artemis\src\Artemis.Core\Plugins\PluginFeature.cs:line 151
   at Artemis.Core.Services.PluginManagementService.EnablePluginFeature(PluginFeature pluginFeature, Boolean saveState, Boolean isAutoEnable) in D:\a\1\s\Artemis\src\Artemis.Core\Services\PluginManagementService.cs:line 621`

**Comment by RobertBeekman** [comment]
Hey, please make sure you have enabled the SDK in iCUE's settings :)

**Comment by Volanaro** [comment]
smh pmsl, thanks XD
