### ISSUE TITLE
Key Press (Ripple) effect refuses to work.

### ISSUE THREAD

**Issue by Lopolin-LP** [Artemis-RGB/Artemis#697]
So... I've tried to use the Key Press Effect, however it won't work... It worked for a brief moment after I first installed Artemis, but then it just broke. Artemis itself doesn't show anything of the effect. Have I misconfigured something?
![image](https://user-images.githubusercontent.com/82715586/166118121-fadd39af-e3b2-4e1c-b6b3-44e6bd0fa040.png)

BTW: this Layer is the top layer.
BTW 2.0: I'm using OpenRGB on my Razer Keyboard, as the Razer service itself failes to start for whatever reason
Keyboard: Blackwidow V3
Mice: Basilisk V2

**Comment by SpyGuy0215** [comment]
Try hiding all other effects and trying the ripple. I don't know if you have the blend mode wrong or something, but on my Blackwidow V3 TKL, something like this happened as well. If it doesn't work when everything else is hidden, then I can't help you there. But if it does, then try experimenting with all the blend modes, as it was working a bit weird for me on my keyboard as well.

**Comment by Lopolin-LP** [comment]
Oh, i had this still open, well: Artemis didn't have a layout (which it should've gotten from OpenRGB), so it couldn't know which keys were pressed. It works now, however I still need a europe/german Version of that because it some keys are pretty wrong.

**Comment by SpyGuy0215** [comment]
> however I still need a europe/german Version

@Lopolin-LP  I actually have a fix for this as well! If you go to **Settings** > **Plugins** and go to the settings of the **Razer** plugin, it gives you the option to turn on emulator devices. If you do, then the emulator controls the keyboard. It will also give you the option to select from lots of keyboard layouts. I haven't checked yet, but I'm pretty sure european layouts are on there. You might have to turn off OpenRGB plugin/removethe Blackwidow V3 from it. Hope this helps!

**Comment by Lopolin-LP** [comment]
@SpyGuy0215 okay thanks! I'll take a look at it tomorr- today after I have slept, I'm just too tired rn probably will message/mention ya if I have a problem with it or something... just one last question: does it require Razer Synapse to be active/open? If yes, then I'll reject it.
good night i guess

**Comment by SpyGuy0215** [comment]
No problem, happy I could help! 

To answer your question, **no**, it does not need Razer Synapse running. I quit all its processes and subprocesses while using OpenRGB to let it work efficiently, and the emulator method worked perfectly.

**Comment by Lopolin-LP** [comment]
@SpyGuy0215 soooo, i just tried it out and it didn't output it to my Keyboard. I had OpenRGB shutdown, even disabled the OpenRGB plugin, both Emulator Devices on and off, rebooted all, nothing. Applying the zones in the Editor was also done, but nothing. It seems like it doesn't "find" the device. It knows it exists (because the name is correct and I didn't set it), but not where i guess. The Input plugin _does_ work, as the inputs of my keyboard are recognized, but still: Nothing get's shown.

**Comment by SpyGuy0215** [comment]
Did you restart your PC? Try if that works. If not, then go into task manager and manually close out anything related to Razer/OpenRGB. As soon as I can get back to my PC (typing this from my phone), I will get back to you with a very detailed guide. Good luck!

**Comment by Lopolin-LP** [comment]
@SpyGuy0215 okay, thank you for all... I did try it again with all Razer/OpenRGB Processes killed (except the RazerChromaStreamServer, which are running from the "SYSTEM"...), and it did not help. Instead:

I've noticed a new issue: the "Default layout file path" is non-existent:
![image](https://user-images.githubusercontent.com/82715586/184383239-85437386-1f5a-49bc-9766-bf520d6b21d3.png)
so, OpenRGB seems to have worked, because it had """such a file""", however Artemis apparently does not. I don't know if this is a problem or not, though. Wait, is that what you meant with this "Emulator Devices" thing?
Another thing to this File thing is: It always throws an error at me if I try to copy the path of it. (hopefully not because of riot's vanguard...)

Next Up: This Key:
![image](https://user-images.githubusercontent.com/82715586/184384380-8d162095-9d16-4a6d-bae2-132a89d9dd65.png)
I can't finish the Input Mappings. So... seems like I need to edit that file manually... somehow, and I don't know where to look, yet.

Also, the Layout is not quite right: The M1-M6 Keys do not exist on my keyboard. (Probably because there's an "old" V3 and a "new" V3...?). And the Num, Roll and Caps-lock Lights are over the arrow keys and the old location is replaced with a volume roll, controlling: volume up/down and mute, and a "media" button, controlling: pause/resume, next and previous. AAAAAAAAAND the Logo is underneath the right alt and fn key.

on top of all this: My Mouse... has two lights... not ~63. Layout missing too...
![image](https://user-images.githubusercontent.com/82715586/184388156-c64b87ab-1ced-4ab9-ad0e-ea35dd3661dc.png)


I'm slowly thinking having stayed at OpenRGB would've been better... it was all compatible, the Input Brush did work, and "rebinding" the Keys did most of the job, of fixing wrong pulsing of buttons, good enough... except this ONE KEY...

Well... If i try to debug all of this there are going to be more problems on the way... amazing.

Anyways, if you have more tricks up your sleeve, it would be of great help.

**Comment by SpyGuy0215** [comment]
Can I just see something? Go to the Razer plugin, and show me the settings. Just send a screenshot. Make sure that the emulator option is enabled. I honestly have no clue what's happening, this never really happened to me. All I can say is if this is too hard, then switch back to OpenRGB. Its probably not worth the time. Or try SignalRGB, another cool program, and see if that helps. That's kinda the problem with these newer open source apps, that they dont have support for everything, and while I know the openrgb and artemis teams are trying their best, it very much still is a beta app.

**Comment by Lopolin-LP** [comment]
here, the settings menu of the razer plugin:
![image](https://user-images.githubusercontent.com/82715586/184424439-86ec52ed-be64-42b6-8c61-cb807436201e.png)
if I try to click "Chroma Emulator" it throws the following error:
`
Stylet.Xaml.ActionNotFoundException: Unable to find method OpenHyperlink on target RazerConfigurationViewModel
   at Stylet.Xaml.ActionBase.AssertTargetSet()
   at Stylet.Xaml.EventAction.InvokeCommand(Object sender, Object e)
   at System.Windows.Navigation.RequestNavigateEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Documents.Hyperlink.NavigateToUri(IInputElement sourceElement, Uri targetUri, String targetWindow)
   at System.Windows.Documents.Hyperlink.DoNavigation(Object sender)
   at System.Windows.Documents.Hyperlink.OnClick()
   at System.Windows.Documents.Hyperlink.DispatchNavigation(Object sender)
   at System.Windows.Documents.Hyperlink.OnMouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.Documents.Hyperlink.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`
And when I try to copy:
`
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard fehlgeschlagen (0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at System.Windows.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Clipboard.SetText(String text)
   at Artemis.UI.Shared.Screens.Exceptions.ExceptionViewModel.CopyException() in D:\a\1\s\Artemis\src\Artemis.UI.Shared\Screens\Exceptions\ExceptionViewModel.cs:line 23
--- End of stack trace from previous location ---
   at Stylet.Xaml.ActionBase.InvokeTargetMethod(Object[] parameters)
   at Stylet.Xaml.CommandAction.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

**Comment by SpyGuy0215** [comment]
At this point, you're better off just leaving it as it is or trying out SignalRGB. It's only going to get more complicated from here, it looks like, and I'm by no means a developer of this project or anyone who knows this much about it. I'm sorry I couldn't help you more :(, and I wish you good luck on your RGB journey :)
