### ISSUE TITLE
Logitech integration plugin stopped working after latest G-Hub update

### ISSUE THREAD

**Issue by RVillani** [Artemis-RGB/Artemis#699]
I'm on Artemis 2.0-1c2fe9 build 20220512.1

After a G-Hub update, my Logitech devices stopped showing up on the surface view. On the Plugins settings page, the Logitech plugin is disabled and trying to enable it displays the toast message below:
![image](https://user-images.githubusercontent.com/1404184/168453394-2d6b5f90-ede7-43d7-8efe-23ced8e33ea7.png)

I've tried restarting Artemis, just in case it had initialized before G-Hub, but the issue persists.
It's weird that G-Hub still showed that there's an integration plugin controlling the devices, so I had to disable it for now to at least control the colors from G-Hub.

I've attached the latest log file with errors from my attempts to enable the plugin.
[Artemis log-20220514_001.log](https://github.com/Artemis-RGB/Artemis/files/8694138/Artemis.log-20220514_001.log)

And this is the exception displayed in the app:
```
System.AggregateException: One or more errors occurred. (RGB.NET threw exception: Failed to initialize Logitech-SDK.)
 ---> Artemis.Core.ArtemisPluginException: RGB.NET threw exception: Failed to initialize Logitech-SDK.
 ---> RGB.NET.Core.RGBDeviceException: Failed to initialize Logitech-SDK.
   --- End of inner exception stack trace ---
   at Artemis.Core.Services.RgbService.AddDeviceProvider(IRGBDeviceProvider deviceProvider) in D:\a\1\s\Artemis\src\Artemis.Core\Services\RgbService.cs:line 182
   at Artemis.Plugins.Devices.Logitech.LogitechDeviceProvider.Enable() in D:\a\1\s\Artemis.Plugins\src\Devices\Artemis.Plugins.Devices.Logitech\LogitechDeviceProvider.cs:line 35
   at Artemis.Core.PluginFeature.InternalEnable() in D:\a\1\s\Artemis\src\Artemis.Core\Plugins\PluginFeature.cs:line 178
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Artemis.Core.PluginFeature.SetEnabled(Boolean enable, Boolean isAutoEnable) in D:\a\1\s\Artemis\src\Artemis.Core\Plugins\PluginFeature.cs:line 151
   at Artemis.Core.Services.PluginManagementService.EnablePluginFeature(PluginFeature pluginFeature, Boolean saveState, Boolean isAutoEnable) in D:\a\1\s\Artemis\src\Artemis.Core\Services\PluginManagementService.cs:line 621
   at Artemis.UI.Screens.Settings.Tabs.Plugins.PluginFeatureViewModel.<UpdateEnabled>b__34_0() in D:\a\1\s\Artemis\src\Artemis.UI\Screens\Settings\Tabs\Plugins\PluginFeatureViewModel.cs:line 162
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Artemis.UI.Screens.Settings.Tabs.Plugins.PluginFeatureViewModel.UpdateEnabled(Boolean enable) in D:\a\1\s\Artemis\src\Artemis.UI\Screens\Settings\Tabs\Plugins\PluginFeatureViewModel.cs:line 162
```

**Comment by RVillani** [comment]
This seems very similar to https://github.com/Artemis-RGB/Artemis.Plugins/issues/91

**Comment by RobertBeekman** [comment]
Hello, I can only suggest trying a fresh reinstall of LGS/GHub here, maybe some files where in use while LGS was updating.
The errors are indeed the same but it's a very generic error :\

**Comment by RVillani** [comment]
Yeah, I understand. Thank you for responding nonetheless.

It's working now after a few PC shutdowns. Go figure...
I haven't reinstalled anything, which is makes it even harder to pinpoint what the issue actually was.
The only thing tried again on this latest OS session was to go to G Hub, left settings menu button, Games & Applications, Integrations tab, click Artemis.UI.exe and toggle "Active" back on. I had done it before several times, but it worked after these few power cycles.

I'll close the issue since it seems to be fixed and I can't really come up with reproduction steps.
