### ISSUE TITLE
Error when accessing Settings for Remote Control Brush

### ISSUE THREAD

**Issue by SpyGuy0215** [Artemis-RGB/Artemis#708]
I got this error when pressing the settings button on the Remote Control brush:
```
Stylet.StyletViewLocationException: Unable to find a View with type Artemis.Plugins.LayerBrushes.RemoteControl.Views.CustomView
   at Stylet.ViewManager.LocateViewForModel(Type modelType)
   at Stylet.ViewManager.CreateViewForModel(Object model)
   at Stylet.ViewManager.CreateAndBindViewForModel(Object model)
   at Stylet.ViewManager.OnModelChanged(DependencyObject targetLocation, Object oldValue, Object newValue)
   at Stylet.Xaml.View.<>c.<.cctor>b__10_0(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at Stylet.WindowManager.ShowDialog(Object viewModel, IViewAware ownerViewModel)
   at Stylet.WindowManager.ShowDialog(Object viewModel)
   at Artemis.UI.Screens.ProfileEditor.LayerProperties.Tree.TreeGroupViewModel.OpenBrushSettings() in D:\a\1\s\Artemis\src\Artemis.UI\Screens\ProfileEditor\LayerProperties\Tree\TreeGroupViewModel.cs:line 79
```

**Comment by RobertBeekman** [comment]
Hi, sorry for not getting back to you, I was busy with a large update.
That same update should've resolved that issue, since I've replaced the entire UI.

![image](https://user-images.githubusercontent.com/8858506/188263091-0c5ed86b-abba-4d3b-b9eb-8fa6f2f4bf68.png)
