### ISSUE TITLE
[Bug Report] Crash when identifying mouse buttons

### ISSUE THREAD

**Issue by Odizinne** [Artemis-RGB/Artemis#772]
Hi,

Artemis crash when i try to identify my mouse inputs.

Output from terminal:
```
[21:53:40 DBG] Start identifying device [Mouse] Razer Basilisk V3 - 339.0.1
[21:53:40 DBG] Stop identifying device [Mouse] Razer Basilisk V3 - 339.0.1
Unhandled exception. System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
   at Avalonia.AvaloniaObject.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 348
   at Avalonia.Input.InputElement.set_IsHitTestVisible(Boolean value) in /_/src/Avalonia.Input/InputElement.cs:line 429
   at FluentAvalonia.UI.Controls.ContentDialog.FinalCloseDialog()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

I'm using PopOS, latest Artemis Linux release this day `1.2023.0326.9`<br/>
Also happening on Debian

![Peek 2023-04-02 00-09](https://user-images.githubusercontent.com/102679854/229316238-2a6a0450-8cfe-4555-811f-2be4f0253721.gif)

**Comment by Odizinne** [comment]
Hi, version 1.2023.0414.7 there is no more crashing, but mouse inputs are not detected. Also the "Cancel" button does not work, so i'm forced to kill Artemis
