### ISSUE TITLE
Not Detecting Steelseries Apex 3

### ISSUE THREAD

**Issue by DovydasTEDS** [Artemis-RGB/Artemis#829]
The plugin detects it but it is not added as a device.
```
[2023-12-25 09:58:56.215] [WRN] [Artemis.Core.Services.DeviceService] Device provider SteelSeriesDeviceProvider has no devices
[2023-12-25 09:58:56.217] [DBG] [Artemis.Plugins.Devices.SteelSeries.SteelSeriesDeviceProvider] Found 1 SteelSeries device(s)
[2023-12-25 09:58:56.218] [DBG] [Artemis.Plugins.Devices.SteelSeries.SteelSeriesDeviceProvider] Found SteelSeries device SteelSeries Apex 3 with PID 0x161A
```

**Comment by DovydasTEDS** [comment]
I don't think this works with any steelseries devices.

**Comment by RobertBeekman** [comment]
Hi and sorry for not responding sooner.
It works with any SteelSeries device supported by their own software, but we need to include each device by it's PID, which you provided in the logs :)

I've added the Apex 3 to the SteelSeries plugin so next Artemis update it will be included. I did set this up as an 8-zone keyboard because that's what it said on their website, so there will probably be a need for a custom layout.

**Comment by DovydasTEDS** [comment]
Hello. There is no activity in the RGB.NET application in Steelseries engine.

**Comment by DovydasTEDS** [comment]
I believe this could be solved by updating the RGB.NET version.

**Comment by DovydasTEDS** [comment]
Hello

**Comment by DovydasTEDS** [comment]
[2024-12-01 18:49:56.320] [WRN] [Artemis.Core.Services.PluginManagementService] Failed to instantiate feature from plugin SteelSeries Devices v1.0.0.0 - 27945704-6edd-48b4-bc0e-319cce9693fc
Artemis.Core.ArtemisPluginException: Failed to instantiate feature
 ---> System.ArgumentException: An item with the same key has already been added. Key: 5658
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Artemis.Plugins.Devices.SteelSeries.SteelSeriesDeviceProvider..ctor(IDeviceService deviceService, ILogger logger) in D:\a\Artemis\Artemis\Artemis.Plugins\src\Devices\Artemis.Plugins.Devices.SteelSeries\SteelSeriesDeviceProvider.cs:line 29
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at DryIoc.Interpreter.TryInterpretSingletonAndUnwrapContainerException(IResolverContext r, Expression expr, ImMapEntry`1 itemRef, Object& result) in /_/src/DryIoc/Container.cs:line 3110
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /_/src/DryIoc/Container.cs:line 11136
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11055
   at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 426
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 392
   at DryIoc.Resolver.Resolve(IResolver resolver, Type serviceType) in /_/src/DryIoc/Container.cs:line 8593
   at Artemis.Core.Services.PluginManagementService.EnablePlugin(Plugin plugin, Boolean saveState, Boolean ignorePluginLock) in D:\a\Artemis\Artemis\Artemis\src\Artemis.Core\Services\PluginManagementService.cs:line 523
   --- End of inner exception stack trace ---

**Comment by DovydasTEDS** [comment]
```
[2024-12-01 18:49:56.320] [WRN] [Artemis.Core.Services.PluginManagementService] Failed to instantiate feature from plugin SteelSeries Devices v1.0.0.0 - 27945704-6edd-48b4-bc0e-319cce9693fc
Artemis.Core.ArtemisPluginException: Failed to instantiate feature
 ---> System.ArgumentException: An item with the same key has already been added. Key: 5658
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Artemis.Plugins.Devices.SteelSeries.SteelSeriesDeviceProvider..ctor(IDeviceService deviceService, ILogger logger) in D:\a\Artemis\Artemis\Artemis.Plugins\src\Devices\Artemis.Plugins.Devices.SteelSeries\SteelSeriesDeviceProvider.cs:line 29
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at DryIoc.Interpreter.TryInterpretSingletonAndUnwrapContainerException(IResolverContext r, Expression expr, ImMapEntry`1 itemRef, Object& result) in /_/src/DryIoc/Container.cs:line 3110
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /_/src/DryIoc/Container.cs:line 11136
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11055
   at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 426
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 392
   at DryIoc.Resolver.Resolve(IResolver resolver, Type serviceType) in /_/src/DryIoc/Container.cs:line 8593
   at Artemis.Core.Services.PluginManagementService.EnablePlugin(Plugin plugin, Boolean saveState, Boolean ignorePluginLock) in D:\a\Artemis\Artemis\Artemis\src\Artemis.Core\Services\PluginManagementService.cs:line 523
   --- End of inner exception stack trace ---
```

**Comment by DovydasTEDS** [comment]
This is the stacktrace / error I get in the logs when trying to load with my Apex 3.
